name: Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: semantic-release
        id: semantic-release
        uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
